[package]
name = "app"
version = "0.1.0"
description = "Cross-platform (Linux, WIndows, MacOS) Desktop GUI system monitor"
authors = ["Pacholo Amit"]
license = "MIT"
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.1.0", features = ["api-all", "system-tray"] }
tauri-plugin-window-state = "0.1"
# chrono = "0.4.22" // May no longer be needed
sysinfo = "0.26.2"
byte-unit = { version ="4.0.14", features = ["serde"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/tauri-plugin-log", branch="dev"}





[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
